export enum COLOR_CODES_FOR_LIGHT_THEME {
  PRIMARY = '#75D9FE',
  SECONDARY = '#3B6C81',
  SHADOW = '#2F3542',
  OUTLINE = '#000000',
  SUCCESS = '#06DEEA',
  ERROR = '#FF7A86',
  WHITE = '#FFFFFF',
  BLACK = '#000000',
  DISABLED = '#6490A7',
  CADET_BLUE = '#A0B4C1',
}

export enum COLOR_CODES_FOR_DARK_THEME {
  PRIMARY = '#75D9FE',
  SECONDARY = '#3B6C81',
  SHADOW = '#B2BEC3',
  OUTLINE = '#FFFFFF',
  SUCCESS = '#06DEEA',
  ERROR = '#FF7A86',
  WHITE = '#FFFFFF',
  BLACK = '#000000',
  DISABLED = '#6490A7',
  CADET_BLUE = '#A0B4C1',
}

export enum PADDINGS {
  SMALL = 8,
  LARGE = 16,
  X_SMALL = 4,
  MEDIUM = 12,
  X_LARGE = 24,
}

export enum IMAGE_DIMENSIONS {
  SMALL = 18,
  LARGE = 32,
  MEDIUM = 28,
  REGULAR = 24,
  X_SMALL = 14,
  XX_SMALL = 12,
}

export enum INPUT_TYPE {
  OUTLINE = 'OUTLINE',
  UNDERLINE = 'UNDERLINE',
  FLOATING_LABEL = 'FLOATING_LABEL'
}

export enum COLUMN_ALIGNMENT {
  START = 'START',
  CENTER = 'CENTER',
  END = 'END'
}

export enum SPACE_DIRECTION {
  LEFT = 'LEFT',
  RIGHT = 'RIGHT',
  TOP = 'TOP',
  BOTTOM = 'BOTTOM'
}

export enum ANIMATION_TYPE {
  TIMING = 'TIMING',
  SPRING = 'SPRING',
}

export enum EXERCISE_TYPE {
  MISSING_WORD = 'MISSING_WORD',
  OTHER = 'OTHER',
}

export enum EXERCISE_BUTTON_TYPE {
  SUBMIT = 'SUBMIT',
  SUCCESS = 'SUCCESS',
  ERROR = 'ERROR'
}
